# In this notebook we r going to cover fundamentals of tensors using tenssor flow

More specifically we're  going to cover
* Introduction to tensors
* Getting information from tensors
* Manipulating tenors
* Tensors &  NumPy
* Using @tf.function
* Using gpu and tpu with tensors


## Introduction to tensors

In [ ]:
#Import tensor flow
import tensorflow as tf
print(tf.__version__)


2.12.0


In [ ]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor(ndim stands for the number of tensor )
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension \of the vector
vector.ndim

1

In [ ]:
# Create a matrix (has mmore than 1 dimension)
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix=tf.constant([[10.,7.],
                            [7.,9.],
                            [8.,10.]],dtype=tf.float16)#specify the  data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7.,  9.],
       [ 8., 10.]], dtype=float16)>

In [ ]:
#what the number of dimensions is of another matrix
another_matrix.ndim

2

In [ ]:
#Let's create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9,],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3


What we've created so far:
* Scalar:a single numeric
* Vector:a number with dimensions
* Matrix:a 2-D array of numbers
* Tensor:an n-dimensional arrray of numbers where n can be any number

Creating variables with tf Variable

In [ ]:
# Create the same tensor with same variable with tensor
import tensorflow as tf
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Let's change a elements in changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
#Try .assign() to change elements
changeable_tensor[0].assign(7)
changeable_tensor


In [ ]:
#Let's tr change unchangeable tesnsor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

# Creating random tensors4
Random tensors are tesnors of some abritary size which contains random numbers




In [ ]:
#Create two random but the same tensor
random_1=tf.random.Generator.from_seed(4)# set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(4)
random_2=random_2.normal(shape=(3,2))

#are they equal
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
#Shuffle a tensor(valuable for when u want to shuffle your data)
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
not_shuffled.ndim


2

In [ ]:
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Shuffle our tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Shuffle our tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
#Shuffle our tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Shuffle our tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise** Read through tensor flow documentations and create 5 diffrent randomseed generatopn and shuffle them

It looks like if we weant our shuffled tensors to be in the same order , we've got to use the global level random seed as well as operation level random seed:
>Follow tensor flow rules

Other ways to create tensors

In [ ]:
#Create tensor of all ones
import tensorflow as tf
tf.ones([20,7])

<tf.Tensor: shape=(20, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all  zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Turn NumPy  arrays into tensors
The main diffrence is tensors can run of a GPU much fasster for numeircal computing

In [ ]:
# You can also turn numpy array into tensor arrays
import numpy as np
numpy_A=np.arange(1, 25, dtype=np.int32)#numpy array from 1 to  25
numpy_A

# X=tf.constant(some_matrix)#capital for matrix or tensor
# y=tf.constant(vector)#non-captial for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(3,8))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

##Getting information from tensors
When dealing with tensor you probably want to be aware of the following attributes
* Shape-length
* Rank-number of dimension
* Axis or dimension- aparticular dimension of a tensor
* Size-total number of items in the tensor

In [ ]:
# Create a rank for a tensor(4 dimensions)
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
 rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of a tensor
print("Datatype of every elemensts:" ,rank_4_tensor.dtype)
print("Rank of tensor:" ,rank_4_tensor.ndim)
print("Shape of tensor:" ,rank_4_tensor.shape)
print("Elemensts along axis:" ,rank_4_tensor.shape[0])
print("Elemensts along last axis:" ,rank_4_tensor.shape[-1])
print("Total number of elemensts:" ,tf.size(rank_4_tensor).numpy())


Datatype of every elemensts: <dtype: 'float32'>
Rank of tensor: 4
Shape of tensor: (2, 3, 4, 5)
Elemensts along axis: 2
Elemensts along last axis: 5
Total number of elemensts: 120


### Indexing Tensors
Tensors can be indexed just like Python lists

In [ ]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
#Get the first two elements of each dimension
rank_4_tensor[:2, :2, :2 , :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get first element from each dimension except last dimension
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor
rank_2_tensor=tf.constant([[10, 7],
                          [ 3, 4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [ ]:
#Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Adding an extra dimension in a tensor
rank_3_tensor=rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to tf new axis
tf.expand_dims(rank_2_tensor,axis=-1)#-1 means expanding last dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)#exapnd the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

###Manipulating tensors(tensor operations)
**Basic Operations**

'+','-','/','*'

In [ ]:
#You can add value to tensor using addition opeartor
import tensorflow as tf
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Multiplication of tensor
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Subtraction of tensor
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#We can use a tensor flow built in function to
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In machine learning matrix multiplication is the basic tensor opeartion

Thwere are two rules our tensors need to follow while mutliplying them
1. The inner dimensions must mamtch
2. The resulting matrix has the shape of the inner dimensions

In [ ]:
#Matrix multiplication in tensorfloe
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix multiplication with python operator"@"
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
#Create a tensor of (3,2) tensor
tensor_1=tf.constant([[1,2,5],
                      [7,2,1],
                      [3,3,3]])
#Create another (2,3) tensor
tensor_2=tf.constant([[3,5],
                      [6,7,],
                      [1,8]])
tensor_1,tensor_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
#Matrix multiplication of the two tensor
tf.matmul(tensor_1,tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#Create a (3,2)tensor
X=tf.constant([[1,2],
               [3,4],
               [5,6]])
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Try to matrix multiplu tensors of same shape
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [ ]:
#Let's reshanpe Y
tf.reshape(Y,shape=(2,3))

In [ ]:
#Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y,shape=(2,3))

In [ ]:
tf.matmul(X, tf.reshape(Y,shape=(2,3)))

In [ ]:
tf.matmul( tf.reshape(X,shape=(2,3)),Y)

In [ ]:
 tf.reshape(X,shape=(2,3)).shape,Y.shape

In [ ]:
#Can do the same with transpose
X,tf.transpose(X),tf.reshape(X,shape=(2,3))
#Transpose flips the axis while the reshape just changes the axis of a tensor

In [ ]:
#Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

**The dot product**

Matrix multiplication is also referred to as the dot product
You can perform matrix multiplication using:
* 'tf.matmul()'
* 'tf.tensordot()'
* '@'

In [ ]:
X,Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Perform the dot product on X and Y ( requires X and Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#Perform matrix multiplication between X and Y transpose
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#Perform matrix multiplication Between X and Y reshape
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#Check the values of Y , reshape Y and transpose Y
print("Normal Y:")
print(Y,"\n")
print("Y reshaped to (2,3)")
print(tf.reshape(Y,shape=(2,3)),"\n")
print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally when performing matrix multiplication when on eof the axes dont line up,you will transpose rather than reshape the tensor to satisfy the matrix multiplication rules

### Changing the datatype of a tensor###


In [ ]:
tf.__version__

'2.12.0'

In [ ]:
# create a new tensor wwith default datatype(float 32)
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C=tf.constant([7,10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
#Change from float 32 bit precision to float 16
D=tf.cast(B, dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
#Change from int 32 to float 32
E=tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16=tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

###Aggregating tensors###

Aggreagting tensors = condesing them from multiple values to smaller values

In [ ]:
#Getting the absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#Getting the absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through following forms of
aggreagration

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Creating a random tensor with values between 0 and 100 off size 50
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([54,  5, 11,  6, 94, 15, 50, 42, 11, 52, 43, 19, 87, 61, 96, 69,  5,
       50, 10, 43, 52,  5, 55, 86,  9, 68, 25, 51, 13, 25, 47, 35, 36, 90,
       62, 75, 55, 96, 31, 23, 98, 95, 83,  2, 65, 82, 48, 23, 13, 19])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Finding the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
np.min(E)

2

In [ ]:
#Finding the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
#Finding the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
#Finding the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2290>

In [ ]:
#Getting the variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=881.11993>

In [ ]:
#Getting the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.683664>

In [ ]:
#Alternative method
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=881>

###Find the positional maximum and minimum



In [ ]:
#Create a new tensor to find positional maximum and minimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index on largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check the equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#Find the minimum using the poositional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

###Squeezing a tensor (Removing all single dimension)


In [ ]:
#Create a random tensor
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

###One-hot encoding tensors

In [ ]:
#Create a list of
some_list=[0,1,2,3]#Could be red,blue,green,purple
depth=4
#One hot encode the list
tf.one_hot(some_list,depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one-hot encoding
tf.one_hot(some_list,depth=4,on_value="abc",off_value="def")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'abc', b'def', b'def', b'def'],
       [b'def', b'abc', b'def', b'def'],
       [b'def', b'def', b'abc', b'def'],
       [b'def', b'def', b'def', b'abc']], dtype=object)>

###Squaring,log,square root

In [ ]:
#Create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Find the square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

###Tensors and NumPy

TensorFlow interacts beatifully with NumPy arrays

**Note**:One of the main differences between a TensorFlow tensor and NumPy array is that a TensorFlow tensor can run on GPU or TPU(for faster processing)

In [ ]:
# create atensor directly from NumPy array
J=tf.constant(np.array([3.,7.,20.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 20.])>

In [ ]:
#Convert our tensor back to a NumPy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 20.]), numpy.ndarray)

In [ ]:
#Convert tensor J to NumPy array
J.numpy(),type(np.array(J))

(array([ 3.,  7., 20.]), numpy.ndarray)

In [ ]:
J=tf.constant([3.])
J.numpy()

array([3.], dtype=float32)

In [ ]:
#The default types of each are slightly different
numpy_J=tf.constant(np.array(np.array([3.,7.,10.])))
tensor_J=tf.constant([3.,7.,10.])
#Check the datatypes
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

###Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sat Jul 15 10:22:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    31W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note**:If you have access to CUDA enabled GPU TensorFlow will automaticallyuse it whenever possible